# Generated by Django 3.2.5 on 2021-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformaInvoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='descriptionOfGoods',
            field=models.TextField(default='LAMINATED LEAF SPRINGS & NUT WITH BOLTS'),
        ),
    ]
