# Generated by Django 3.2.5 on 2021-09-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.TextField()),
                ('billDate', models.DateField()),
                ('otherReferences', models.TextField(blank=True, null=True)),
                ('grNo', models.TextField(blank=True, null=True)),
                ('termsOfPayment', models.TextField(blank=True, null=True)),
                ('natureOfContract', models.TextField(blank=True, null=True)),
                ('preCarriage', models.TextField(blank=True, null=True)),
                ('vesselFlightNo', models.TextField(blank=True, null=True)),
                ('portOfLoading', models.TextField(blank=True, null=True)),
                ('portOfDischarge', models.TextField(blank=True, null=True)),
                ('finalDestination', models.TextField(blank=True, null=True)),
                ('products', models.TextField()),
                ('freightCharges', models.FloatField()),
                ('totalSales', models.FloatField()),
                ('currency', models.TextField()),
                ('ladingDate', models.DateField(blank=True, null=True)),
                ('billOfLadingNo', models.TextField(blank=True, null=True)),
                ('totalBoxes', models.IntegerField()),
                ('lcNo', models.TextField(blank=True, null=True)),
                ('lcDate', models.DateField(blank=True, null=True)),
                ('contractNo', models.TextField(blank=True, null=True)),
                ('contractDate', models.DateField(blank=True, null=True)),
                ('shippingBillNo', models.TextField(blank=True, null=True)),
                ('shippingBillDate', models.DateField(blank=True, null=True)),
                ('exchangeNo', models.TextField(blank=True, null=True)),
                ('exchangeDate', models.DateField(blank=True, null=True)),
                ('consigneeBank', models.TextField(blank=True, null=True)),
                ('consigneeAccount', models.TextField(blank=True, null=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
