# Generated by Django 3.2.5 on 2021-09-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_bill_shipingmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='shipingMark',
            new_name='shippingMark',
        ),
    ]
