# Generated by Django 3.2.5 on 2021-09-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_rename_shipingmark_bill_shippingmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='shippingMark',
        ),
    ]
