# Generated by Django 3.2.5 on 2021-09-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_remove_bill_shippingmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='shipMark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
