# Generated by Django 3.2.5 on 2021-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_bill_shipmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='checkerForCForFOB',
            field=models.TextField(default='C&F'),
        ),
    ]
