# Generated by Django 3.2.5 on 2021-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_bill_checkerforcforfob'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amtDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
