# Generated by Django 3.2.5 on 2021-10-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_bill_pdfconsignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='checkerForCForFOB',
            field=models.TextField(blank=True, null=True),
        ),
    ]
