# Generated by Django 3.2.5 on 2022-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20211016_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='otherThanConsigne',
            field=models.TextField(default='None'),
        ),
    ]
