# Generated by Django 4.0.4 on 2022-05-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20220204_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='withComponents',
            field=models.TextField(default='(With Components)'),
        ),
    ]
