# Generated by Django 4.0.4 on 2022-05-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_bill_withcomponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='descri',
            field=models.TextField(default='(add description)'),
        ),
    ]
