# Generated by Django 3.2.5 on 2021-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.TextField(primary_key=True, serialize=False)),
                ('company_address', models.TextField()),
                ('company_country', models.TextField()),
            ],
        ),
    ]
