# Generated by Django 3.2.5 on 2021-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.TextField(primary_key=True, serialize=False)),
                ('hsnCode', models.TextField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
